[
    {
        "name":"创建GUID",
        "apis":[
            {
                "name":"getGUID",
                "type":"function",
                "params":[
                    {"name":"len","type":"Number","desc":"生成的guid的长度"},
                    {"name":"radix2","type":"Number","desc":"生成的guid的数制，如2,10,16"}
                ],
                "demoCodeRefs":[
                    {
                        "name":"getGUID实例",
                        "desc":"演示getGUID基本用法",
                        "type":"example",
                        "codeUrl":"/demo/demoData/OneLib.GUID/example.getGUID.html",
                        "cssUrls":[
                        ],
                        "javascriptUrls":[
                        ]
                    }
                ]
            },
            {
                "name":"getGUID2",
                "type":"function",
                "params":[
                    {"name":"len","type":"Number","desc":"生成的guid的长度"},
                    {"name":"radix","type":"Number","desc":"生成的guid的数制，如2,10,16"}
                ],
                "demoCodeRefs":[
                    {
                        "name":"getGUID实例",
                        "desc":"演示getGUID基本用法",
                        "type":"real",
                        "codeUrl":"/demo/demoData/OneLib.GUID/example.getGUID2.html",
                        "cssUrls":[
                        ],
                        "javascriptUrls":[
                        ]
                    }
                ]
            },
            {
                "name":"getGUID3",
                "type":"function",
                "params":[
                    {"name":"len","type":"Number","desc":"生成的guid的长度"},
                    {"name":"radix","type":"Number","desc":"生成的guid的数制，如2,10,16"}
                ],
                "demoCodeRefs":[
                    {
                        "name":"getGUID实例",
                        "desc":"演示getGUID基本用法",
                        "type":"example",
                        "codeUrl":"/demo/demoData/OneLib.GUID/example.getGUID3.html",
                        "cssUrls":[
                        ],
                        "javascriptUrls":[
                        ]
                    }
                ]
            },
            {
                "name":"getGUID4",
                "type":"function",
                "params":[
                    {"name":"len","type":"Number","desc":"生成的guid的长度"},
                    {"name":"radix","type":"Number","desc":"生成的guid的数制，如2,10,16"}
                ],
                "demoCodeRefs":[
                    {
                        "name":"getGUID实例",
                        "desc":"演示getGUID基本用法",
                        "type":"example",
                        "codeUrl":"/demo/demoData/OneLib.GUID/example.getGUID4.html",
                        "cssUrls":[
                        ],
                        "javascriptUrls":[
                        ]
                    }
                ]
            }
        ]
    },
    {
        "name":"创建GUID2",
        "apis":[
            {
                "name":"getGUID5",
                "type":"function",
                "params":[
                    {"name":"len","type":"Number","desc":"生成的guid的长度"},
                    {"name":"radix","type":"Number","desc":"生成的guid的数制，如2,10,16"}
                ],
                "demoCodeRefs":[
                    {
                        "name":"getGUID实例",
                        "desc":"演示getGUID基本用法",
                        "type":"example",
                        "codeUrl":"/demo/demoData/OneLib.GUID/example.getGUID5.html",
                        "cssUrls":[
                        ],
                        "javascriptUrls":[
                            "http://localhost:9527/test/OneLib.ScriptLoader/qunitCase/module_a.js",
                            "http://localhost:9527/test/OneLib.ScriptLoader/qunitCase/module_b.js",
                            "http://localhost:9527/test/OneLib.ScriptLoader/qunitCase/module_c.js"
                        ]
                    }
                ]
            },
            {
                "name":"getGUID6",
                "type":"function",
                "params":[
                    {"name":"len","type":"Number","desc":"生成的guid的长度"},
                    {"name":"radix","type":"Number","desc":"生成的guid的数制，如2,10,16"}
                ],
                "demoCodeRefs":[
                    {
                        "name":"getGUID实例",
                        "desc":"演示getGUID基本用法",
                        "type":"example",
                        "codeUrl":"/demo/demoData/OneLib.GUID/example.getGUID6.html",
                        "cssUrls":[
                        ],
                        "javascriptUrls":[
                        ]
                    }
                ]
            },
            {
                "name":"getGUID7",
                "type":"function",
                "params":[
                    {"name":"len","type":"Number","desc":"生成的guid的长度"},
                    {"name":"radix","type":"Number","desc":"生成的guid的数制，如2,10,16"}
                ],
                "demoCodeRefs":[
                    {
                        "name":"getGUID实例",
                        "desc":"演示getGUID基本用法",
                        "type":"example",
                        "codeUrl":"/demo/demoData/OneLib.GUID/example.getGUID7.html",
                        "cssUrls":[
                        ],
                        "javascriptUrls":[
                        ]
                    }
                ]
            },
            {
                "name":"getGUID8",
                "type":"function",
                "params":[
                    {"name":"len","type":"Number","desc":"生成的guid的长度"},
                    {"name":"radix","type":"Number","desc":"生成的guid的数制，如2,10,16"}
                ],
                "demoCodeRefs":[
                    {
                        "name":"getGUID实例",
                        "desc":"演示getGUID基本用法",
                        "type":"example",
                        "codeUrl":"/demo/demoData/OneLib.GUID/example.getGUID8.html",
                        "cssUrls":[
                        ],
                        "javascriptUrls":[
                        ]
                    }
                ]
            }
        ]
    }
]